version: "3.8"

services:
  genie:
    build:
      context: .
      dockerfile: Dockerfile
    image: genie-worksheets:dev
    env_file:
      - dev.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/app
    working_dir: /app
    tty: true
    user: root 