# This configuration file defines the setup for how ChainLite calls various LLM APIs, and how it logs LLM inputs/outputs.
# To configure it:
# 1. Set directories containing the prompt files under the `prompt_dirs` section.
# 2. Adjust logging settings and optionally specify which prompts you would like to skip in the `prompt_logging` section.
# 3. Configure LLM endpoints under the `llm_endpoints` section, specifying the API base URL, version (if needed), API key (if needed), 
#    and the mapping of model names to their respective deployment identifiers. The name on the left-hand side of each mapping is "engine", the shorthand
#    you can use in your code when calling llm_generation_chain(engine=...).
#    The name on the right side-hand is the "model", the specific name that LiteLLM expects: https://docs.litellm.ai/docs/providers
#    Note that "engine" names should be unique within this file, but "model" names do not have to be unique.
# 4. Follow the examples provided for Azure, OpenAI, Groq, Together, Mistral, and local models as needed, and remove unused llm endpoints.

prompt_dirs: # List of directories containing prompt files, relative to the location of this file
  - "src/worksheets/kraken/prompts/"  # Directory for knowledge agent prompts
  - "src/worksheets/prompts/"


litellm_set_verbose: false  # Verbose logging setting for LiteLLM
prompt_logging:
  log_file: "./prompt_logs.jsonl"  # Path to the log file for prompt logs, relative to the location of this file
  prompts_to_skip:
    - "tests/test.prompt"  # List of prompts to exclude from logging, relative to the location of this file

# Configuration for different LLM endpoints
llm_endpoints:
  # Example configuration for OpenAI models via Azure API
  - api_base: YOUR BASE URL  # Base URL for Azure OpenAI API
    api_version: "2024-08-01-preview"  # API version for Azure OpenAI
    api_key: "AZURE_OPENAI_KEY"  # API key for Azure OpenAI as defined in the environment variables
    engine_map:  # Mapping of model names to Azure deployment identifiers prepended by "azure/"
      gpt-35-turbo: azure/gpt-35-turbo
      gpt-35-turbo-16k: azure/gpt-35-turbo-16k
      gpt-35-turbo-instruct: azure_text/gpt-35-turbo-instruct
      gpt-4: azure/gpt-4
      gpt-4-32k: azure/gpt-4-32k
      gpt-4o: azure/gpt-4o
      gpt-4o-mini: azure/gpt-4o-mini
      gpt-4.1: azure/gpt-4.1
      gpt-4.1-mini: azure/gpt-4.1-mini
