site_name: GenieWorksheets
site_url: https://worksheets.genie.stanford.edu/
repo_url: https://github.com/stanford-oval/genie-worksheets/
nav:
  - Home:
    - What is GenieWorksheets?: index.md
    - Getting Started:
      - Installation: installation.md
      - Creating an Agent: getting_started.md
      - Creating Prompts: prompt.md
    - Core Concepts:
      - Dialogue State: dialogue_state.md
      - Agent Policy: agent_policy.md
  - Examples:
    - List of Examples: examples.md
    - Restaurant Reservation: restaurant_reservation.md
    - Ticket Submission: ticket_submission.md
    - Course Enrollment: course_enrollment.md
  - API Reference:
    - Core Modules:
      - Environment: api/environment.md
      - Agent: api/agent.md
      - Knowledge: api/knowledge.md
      - From Spreadsheet: api/from_spreadsheet.md
    - Utility Modules: api/utils.md
    

theme:
  name: material
  logo: assets/genie_worksheets_circle.png
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  icon:
    repo: fontawesome/brands/github

  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - toc.follow
    - navigation.footer
    # - toc.integrate
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_if_no_docstring: true
            show_signature: true
            show_signature_annotations: true
            show_source: true
            show_bases: true
            show_type_annotations: true
            inherited_members: true
            unwrap_annotated: true
            merge_init_into_class: false
            separate_signature: true
            show_root_heading: true
            show_root_full_path: true
            show_object_full_path: false
            show_category_heading: true
            line_length: 80
            members_order: source
            docstring_section_style: table
            show_submodules: true
            filters: []  # Ensure no members are excluded
            preload_modules: 
              - src.worksheets
  - autorefs

markdown_extensions:
  - abbr
  - admonition
  - def_list
  - footnotes
  - md_in_html
  - tables
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

